version: '2'
services:
  registrator:
    image: gliderlabs/registrator
    container_name: registrator
    network_mode: "host"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    command: consul://localhost:8500
