version: '2'
services:
  consul:
    image: consul
    network_mode: host
    command: agent -config-dir /consul/config -server -bootstrap -ui
    volumes:
      - ${COMPOSEROOT}/consul/consul.json:/consul/config/consul.json
    environment:
      - CONSUL_ALLOW_PRIVILEGED_PORTS=

  registrator:
    depends_on:
      - consul
    image: gliderlabs/registrator
    network_mode: host
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: consul://${INTRANETIP}:8500
