version: '2'
services:
  samba:
    image: dperson/samba 
    container_name: samba
    hostname: samba
    environment:
      - TZ=Asia/Hong_Kong
    ports:
      - 139:139
      - 445:445
    volumes:
      - ${COMPOSEROOT}/samba:/share
    command: -u "user;password" -s "share;/share;yes;no;no"