version: '2'
services:
  mobile_mongo:
    image: mongo 
    container_name: mobile_mongo
    hostname: mobile_mongo
    ports:
      - 27017
    volumes:
      - ${COMPOSEROOT}/mobile/data:/data/db
    command: mongod --directoryperdb

  mobile:
    depends_on:
      - mobile_mongo
    image: twhtanghk/mobile
    container_name: mobile
    hostname: mobile
    ports:
      - 1337
    volumes:
      - ${COMPOSEROOT}/mobile/conf:/usr/src/app/config/env
      - /etc/ssl/certs:/etc/ssl/certs
      - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates
