version: "2"

services:
  composeui:
    restart: always
    image: francescou/docker-compose-ui
    ports:
      - 5000
    working_dir: /opt/docker-compose-projects/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/opt/docker-compose-projects
    env_file:
      - ../.env
