version: '2'
services:
  echo:
    image: solsson/http-echo
    ports: 
      - 80
    env_file:
      - ../.env

  sails_proxy:
    depends_on:
      - echo
    image: twhtanghk/sails_proxy
    external_links:
      - mongo
    networks:
      - mongo_default
    ports:
      - 1337:1337
    env_file:
      - ./.env
      - ../.env

networks:
  mongo_default:
    external: true
