version: '2'
services:
  consul1:
    image: progrium/consul
    container_name: consul1
    hostname: consul1
    network_mode: host
    command: -server -bootstrap

  registrator:
    depends_on:
      - consul1
    image: gliderlabs/registrator
    container_name: registrator
    hostname: registrator
    network_mode: host
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: consul://localhost:8500

  'dns-template':
    depends_on:
      - consul1
    image: 'twhtanghk/dns-template'
    container_name: 'dns-template'
    hostname: 'dns-template'
    ports:
      - 1337
    volumes:
     - ${COMPOSEROOT}/dns-template:/usr/src/app/template
